trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: secret_token_file
  inputs:
    secureFile: 'settings.xml'

- task: Maven@4
  inputs:
    mavenPOMFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenOptions: '-Xmx1024m -Drevision=$(Build.BuildNumber)'
    options: '-s $(secret_token_file.secureFilePath)'
    goals: 'deploy'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: '20.167.43.89'
    contents: 'release/devops-assignment.war'
    targetFolder: '/var/lib/tomcat10/webapps/'
    cleanTargetFolder: true

- task: SSH@0
  inputs:
    sshEndpoint: '20.167.43.89'
    runOptions: 'commands'
    commands: 'sudo service tomcat10 restart'
