trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: secret_token_file
  inputs:
    secureFile: 'settings.xml'

- task: Maven@4
  inputs:
    mavenPOMFile: 'pom.xml'
    options: '-s $(secret_token_file.secureFilePath)'
    goals: 'deploy'

#- task: CopyFiles@2
#  inputs:
#    Contents: './target/devops-assignment.war'
#    TargetFolder: '$(build.artifactstagingdirectory)'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'

