trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: secret_token_file
  inputs:
    secureFile: 'settings.xml'

- task: Maven@4
  inputs:
    mavenPOMFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenOptions: '-Xmx1024m -Drevision=$(Build.BuildNumber)'
    options: '-s $(secret_token_file.secureFilePath)'
    goals: 'test'

- task: Maven@4
  inputs:
    mavenPOMFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenOptions: '-Xmx1024m -Drevision=$(Build.BuildNumber)'
    options: '-s $(secret_token_file.secureFilePath)'
    goals: 'deploy'

- task: CmdLine@2
  inputs:
    script: 'tree $(System.DefaultWorkingDirectory)'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'TEST-*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/target/surefire-reports/'
    failTaskOnFailedTests: true
    failTaskOnFailureToPublishResults: true
    publishRunAttachments: true
